### PR TITLE
Channel clarifications.

### PR DESCRIPTION
**Pull request by briandailey**
This was inspired by [this video](https://en.blog.wordpress.com/2020/03/06/a-crash-course-in-remote-management/) and particular this slide:

image

### CODE REVIEW

**Comment by briandailey** [comment]
Looking for feedback / tweaks from the team on this one.

**Comment by rousell** [comment]
I think it could be good to document that we generally want to cross-pollinate conversations that occur in slack channels by linking relevant conversations in github tickets, google docs, etc. (and that you can't link private slack conversations)

**Comment by upjohnc** [comment]
I think it is a good statement of the use of technology.  Especially calling out the usage of video chat as a normal communication medium.

**Review by sburns — APPROVED** [review]
Explicit > Implicit!

**Pull request merged**
